name: 'analytics'
version: '1.0.0'
config-version: 2

profile: 'analytics'


model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +query_tag: dbt-ng
  +persist_docs:
    relation: true
    columns: true

  analytics:

    staging:
      +materialized: table
      +schema: staging

    marts:
      +materialized: table
      employment:
        +schema: employment
      reporting:
        +schema: reporting